import random

nums = [-1, 0, 1, 2, -1, -4]
unique_triplets = set()  # Using a set automatically prevents duplicate answers

# Run the loop 1000 times instead of infinitely
for _ in range(1000):
    # Pick random INDEXES instead of values to ensure we don't pick the exact same slot twice
    idx1, idx2, idx3 = random.sample(range(len(nums)), 3)
    
    x = nums[idx1]
    y = nums[idx2]
    z = nums[idx3]
    
    if x + y + z == 0:
        # Sorting ensures [-1, 0, 1] and [0, 1, -1] are treated as the exact same triplet
        triplet = tuple(sorted([x, y, z]))
        unique_triplets.add(triplet)

# Convert back to a list of lists to print
result = [list(t) for t in unique_triplets]
print("Found Triplets:", result)
# Output: [[-1, -1, 2], [-1, 0, 1]]


random.sample(range(len(nums)), 3)

min(4, 6): The min() function picks the smaller number, which is 4.

words = ["flower", "flow", "flight"]
# zip(*words) yields: ('f', 'f', 'f'), then ('l', 'l', 'l'), then ('o', 'o', 'i')...


 # If all characters in the group are identical, set(characters) will have a size of 1
    if len(set(characters)) == 1:


from collections import Counter

# This matches the char_list generated by your loops
char_list = ['f', 'l', 'o', 'w', 'e', 'r', 'f', 'l', 'o', 'w', 'f', 'l', 'i', 'g', 'h', 't']
counts = Counter(char_list)

words.insert(0, "flower")

''.join()
only applicable for alphabets and not for numbers


# Reverse and join all at once
a = ''.join(str(x) for x in l1[::-1])  # Result: "342"
b = ''.join(str(x) for x in l2[::-1])  # Result: "465"

class Solution:
    def twoSum(self, nums, target):
        for i in range(len(nums)):
            for j in range(i + 1, len(nums)):
                if nums[i] + nums[j] == target:
                    return [i, j]


nums = [2, 11, 7, 15]

# Find index of the largest number (15)
max_index = nums.index(max(nums))

print(max_index)  
# Output: 3
